### ISSUE TITLE
special treatment of certain headers 特殊处理某些标题

### ISSUE THREAD

**Issue by TigerHall** [h-hg/docsify-image-caption#1]
也许可以考虑针对某些图片，加上描述但不用形成图片标题
Maybe consider adding a description but not a title for some images

1. ![有标题 have caption name](https://github.com/h-hg.png "标题caption name")

  标题caption name

2. ![无标题 no caption name](https://github.com/h-hg.png "标题caption name 🚫 :nocaption")

  标题caption name 🚫 :nocaption

对图片2描述不进行标题生成 No title generation for the description of picture 2

**Comment by h-hg** [comment]
Thanks for your suggestion. The related usage can be found in the [docs](https://h-hg.github.io/docsify-image-caption/#/).
（谢谢你的建议。相关的使用说明可以在 [文档](https://h-hg.github.io/docsify-image-caption/#/) 中找到。）
